using Microsoft.EntityFrameworkCore;
using ReCallVocabulary.Data_Access;

namespace ReCallVocabulary
{
    public partial class App : Application
    {
        public static string fileWithCurrentDBName { get; private set; }
        private static DictionaryContext? activeContext;

        internal static DictionaryContext? ActiveContext
        {
            get => activeContext;
            set
            {
                File.WriteAllText(fileWithCurrentDBName, Path.GetFileName(value.MyPath));
                activeContext = value;
            }

        }

        public App()
        {
            InitializeComponent();
#if WINDOWS
            fileWithCurrentDBName = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "currentDBName.txt");
            if (!File.Exists(fileWithCurrentDBName))
            {
                var myFile = File.Create(fileWithCurrentDBName);
                myFile.Close();
                File.WriteAllText(fileWithCurrentDBName,"autogenerated.db");
            }
#elif ANDROID

            fileWithCurrentDBName = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
            if (!Directory.Exists(fileWithCurrentDBName))
            {
                Directory.CreateDirectory(fileWithCurrentDBName);               
            }
            fileWithCurrentDBName = Path.Combine(
            fileWithCurrentDBName, "currentDBName.txt");

            if(!File.Exists((fileWithCurrentDBName)))
            {
var myFile = File.Create(fileWithCurrentDBName);
                myFile.Close();
                File.WriteAllText(fileWithCurrentDBName,"autogenerated.db");
            }
#endif
            ActiveContext = new DictionaryContext(File.ReadAllText(fileWithCurrentDBName));
            MainPage = new AppShell();
        }
    }
}
