using Microsoft.EntityFrameworkCore;
using ReCallVocabulary.Data_Access;

namespace ReCallVocabulary
{
    public partial class App : Application
    {
        private static string fileWithCurrentDBName;
        private static DictionaryContext? activeContext;
        internal static DictionaryContext? ActiveContext
        {
            get => activeContext;
            set
            {
                File.WriteAllText(fileWithCurrentDBName, Path.GetFileName(value.MyPath));
                activeContext = value;
            }

        }
        public App()
        {
            InitializeComponent();
            fileWithCurrentDBName = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "currentDBName.txt");
            if (!File.Exists(fileWithCurrentDBName))
            {
                var myFile = File.Create(fileWithCurrentDBName);
                myFile.Close();
                File.WriteAllText(fileWithCurrentDBName,"autogenerated.db");
            }

            ActiveContext = new DictionaryContext(File.ReadAllText(fileWithCurrentDBName));
            MainPage = new AppShell();
        }
        protected override void OnStart()
        {
            base.OnStart(); 
        }

    }
}
