using Microsoft.EntityFrameworkCore;

namespace ReCallVocabulary.Data_Access
{
    public class DictionaryContextManager
    {
        private readonly IServiceProvider _serviceProvider;
        private DictionaryContext _currentDbContext;

        public DictionaryContextManager(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
            SwitchDatabase("autogenerated.db"); // Default database
        }

        public DictionaryContext CurrentDbContext => _currentDbContext;

        public void SwitchDatabase(string databaseName)
        {
            _currentDbContext?.Dispose(); // Dispose old instance

            _currentDbContext = new DictionaryContext(databaseName);
        }
    }
}
